image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
    - esbenp.prettier-vscode@5.1.3:t532ajsImUSrA9N8Bd7jQw==